# Generated by Django 5.1.6 on 2025-02-19 06:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('شنوایی', 'شنوایی'), ('گفتار درمانی', 'گفتار درمانی'), ('کار درمانی', 'کاردرمانی'), ('فیزیو تراپی', 'فیزیوتراپی'), ('آرترز', 'آرترز'), ('پروتز', 'پروتز')], default='Doctor care', max_length=50)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('8 AM', '8:30 AM'), ('8:30 AM', '9 AM'), ('9 AM', '9:30 AM'), ('9:30 AM', '10 AM'), ('10: AM', '10:30 AM'), ('10:30 AM', '11 AM'), ('11 AM', '11:30 AM'), ('11:30 AM', '12 AM'), ('3 PM', '3:30 9M'), ('3:30 PM', '4 PM'), ('4 PM', '4:30 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7 PM'), ('7:30 PM', '7:30 PM')], default='3 PM', max_length=10)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
