# Generated by Django 5.1.6 on 2025-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Hearing', 'شنوایی'), ('Speech therapy', 'گفتار درمانی'), ('Occupational therapy', 'کاردرمانی'), ('Physiotherapy', 'فیزیوتراپی'), ('Arthritis', 'آرتروز'), ('Prosthesis', 'پروتز')], default='Doctor care', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('8 صبح', '8:30 صبح'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7 PM'), ('7:30 PM', '7:30 PM')], default='3 PM', max_length=10),
        ),
    ]
