# Generated by Django 5.1.6 on 2025-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_appointment_service_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('شنوایی', 'شنوایی'), ('Speech therapy', 'Speech therapy'), ('Occupational therapy', 'Occupational therapy'), ('Physiotherapy', 'Physiotherapy'), ('Arthritis', 'آArthritis'), ('Prosthesis', 'Prosthesis')], default='Doctor care', max_length=50),
        ),
    ]
